### ISSUE TITLE
Support variable-length registers in `device.yml` register specifications

### ISSUE THREAD

**Issue by PathogenDavid** [harp-tech/protocol#116]
* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary

Right now the length of a register as defined in `device.yml` is always a fixed length, this proposal seeks to remove this restriction. The protocol has no such restriction.

## Motivation

This has mainly come up due to string registers like the device name register and the proposed [semantic version register](https://github.com/harp-tech/protocol/pull/68).

Future uses might include sending back error messages from the device or uploading firmware/configuration blobs.

I think it could be interesting for a device to be able to regurgitate its own `device.yml`. (Similar to how some APIs expose a well-defined machine-readable endpoint on how to interact with them, EG: [YouTube](https://youtube.googleapis.com/$discovery/rest?version=v3).)

## Detailed Design

(Exact implementation open to discussion)

If it doesn't run up against the generator implementations, cleanest would be allowing a special value for `length`, IE:

```yaml
DocumentationUrl:
  address: 42
  type: U8
  length: variable
  interfaceType: string
  access: Read
  description: The documentation URL associated with this device
```

## Drawbacks

In an embedded context it can be somewhat problematic to deal with variable-length things, particularly on lower-end MCUs. (As a convention we might not allow writable variable-length registers in the core register set.)

## Alternatives

* Continue using fixed-length strings padded with `\0` (as `R_DEVICE_NAME` is today.)
* Could omit length and declare that the variable length comes from the `interfaceType`
  * However we've talked about wanting `interfaceType` to be mostly optional so that is somewhat problematic.
  * We could say generators treat all unknown interface types as variable-length arrays of the payload type. Would be silly in some cases but still usable.

## Unresolved Questions

* Exact implementation TBD
* Should we optionally allow specifying an upper bound for the sake of writable registers?
  * Alternatively, do we want a way to query what a device is capable of having written to it?
  * Both could be hard to define in some circumstances and arbitrary in others.
  * For queries, could allow a response of "unspecified" or just `UInt16.MaxValue`.
  * Could easily come later when a need arises.

## Design Meetings

TBD

**Comment by bruno-f-cruz** [comment]
- @glopesdev suggests using `null` instead of `0` to specify variable-length messages in the `device.yml`

Regarding the standard logging format:
- registers should probably be demux during acquisition time
- harp-python would have to be updated to make a "joint" table

**Comment by PathogenDavid** [comment]
Thoughts from SRM today:
 
* `R_TAG` is another good candidate
* Need further analysis on how this might interact with logging and log parsing. (Don't think there's anything insurmountable, just need to dot our T's and cross our I's.)

**Comment by PathogenDavid** [comment]
Another good candidate for this functionality is the fictional `R_POROTOCOL_CAPABILITIES` register described [in this thread](https://github.com/orgs/harp-tech/discussions/136).

**Comment by PathogenDavid** [comment]
One final item for the wishlist before I disappear into the fog:

I really wish `R_SERIAL_NUMBER` was a variable-length array of U8. 2 bytes of entropy is woefully inadequate when the serial number isn't assigned manually, such as if it's derived from some high-volume component like the ID on a flash chip or the processor.

For backwards compatibility, cores could return the lower 16 bits for a READ of U16 and return a variable-length array for a read of U8.

**Comment by bruno-f-cruz** [comment]
Leaving this here, but there may be an issue I am not seeing. One idea that came to mind was to implement this as a sort of "variadic" payload in the device.yml and combine it with https://github.com/harp-tech/protocol/issues/40 and https://github.com/harp-tech/protocol/issues/118

For instance:
```yml
  Data:
    access: Event
    address: 32
    type: byte
    length: null # We will probably still need a sentinel value here
    payloadSpec:
      AlwaysExists:
        offset: 0
      AlwaysExistsToo:
        offset: 1
      AJsonString:
        offset: 2
        length: null
        interfaceType: str
```


This would create the following struct:

```csharp
public struct DataPayload
{
    public byte AlwaysExists;
    public byte AlwaysExistsToo;
    public str AJsonString;
}
```

Without an `interfaceType`, the variadic defaults to an array of the specified message type:

```yml
  Data:
    access: Event
    address: 32
    type: float
    length: null # We will probably still need a sentinel value here
    payloadSpec:
      VariableLengthArray:
        length: null
```
which gives rise to:

```csharp
public struct DataPayload
{
    public float[] VariableLengthArray;
}
```

This implementation relies on the following assumptions:
1. There can only ever be a single `length: null` per payloadSpec
2. Such null-length element MUST always be the last portion of the message. Since we do not have a second delimiter to use for internal parsing, we need to rely on the delimiter of the actual harp message
3. In messages with payloadSpec that have elements BEFORE the null-length portion, we assume that those are always required.
4. This is a kinda of a cool way to ensure backwards compatibility with current registers that may need a variable-length portion, since at the limit you could simply return an empty array for the null-length portion.
