### ISSUE TITLE
Add support for versioning core register schema

### ISSUE THREAD

**Issue by glopesdev** [harp-tech/protocol#22]
Following the developments in harp-tech/reflex-generator#57 and harp-tech/protocol#21, we started wondering there is currently no way of versioning the common YML file itself.

One option to workaround this is to add an additional schema for the core, e.g. `core.json` which would require an extra property on these YML files which is the core version. The number added there would have to match the core version used to implement the device firmware for each device.

There might be a few more details to think about related to how we merge this common YML file with the individual device schemas, but this versioning will be important so we don't accidentally start including new registers in a joint device map which are not actually implemented by the device firmware if it is still using an older harp core.

**Comment by glopesdev** [comment]
Are core registers tied to a specific core implementation version? no, they are tied to specification version
 - coreVersionHigh / Low should return the version of the core firmware implementation (atmel core or pico core)
 - device.yml needs to declare which version of the core specification it implements

Outstanding questions:
  - are we ok with using "draft-xx" for versioning / url of meta-schema file
  - what name should this field have?
  - where do we need to change meta-schema? is it enough to add a new field to `device.json`? do we need to also add a `core.json` to use as meta-schema for `common.yml`?
  - are we ok with the name `common.yml`?
  - should the core version high / low registers return the version number of the `common.yml` file that it implements?
    - if yes, do we also need to return the version of the core firmware anyway? maybe not required since there is a tight link between firmware version and harp core firmware version (if core changes, firmware version needs to bump up)

**Comment by glopesdev** [comment]
One important consideration is there can be releases of the same device firmware version for different core implementations, for compatibility reasons. This suggests we probably want an extra register to store the specification version.

A proposal which was suggested is to create a new single register containing all version information (hardware, firmware, core, specification) encoded as a payload specification. This would allow us to extend the range of versioning (e.g. to include a new patch version number, the new specification versions, etc) as well as providing a single register to retrieve the entire version information in a single call.

### Example definition

```yaml
  VersionInfo:
    address: 15
    type: U8
    length: 12
    access: Read
    description: Stores the version info for the device hardware, firmware, core, and specification used.
    payloadSpec:
      HardwareVersion:
        offset: 0
        description: Specifies the hardware version of the device.
        interfaceType: HarpVersion
      FirmwareVersion:
        offset: 3
        description: Specifies the firmware version of the device.
        interfaceType: HarpVersion
      CoreVersion:
        offset: 6
        description: Specifies the core version of the device.
        interfaceType: HarpVersion
      SpecVersion:
        offset: 9
        description: Specifies the spec version of the device.
        interfaceType: HarpVersion
```

### Outstanding questions

- Name of the register
- Number of version components (2 or 3)?
- Order of version components (hardware, firmware, core, spec or something else?)
- Interface type used to represent version in Bonsai.Harp, there is currently a `HarpVersion` type already, but it only includes two components (high / low)
