### ISSUE TITLE
Heterogenous register types in yaml schema

### ISSUE THREAD

**Issue by bruno-f-cruz** [harp-tech/protocol#40]
@Poofjunior Thanks for the great input and raising this requirement, I agree having more flexibility in passing around packed custom structures with possibly heterogeneous types is important.

Following the meeting, I was playing around with the YAML schema and actually there is a small kink that doesn't allow it to represent heterogeneous types out-of-the-box (yet). It is definitely fixable though and this is a use case we should indeed support so I will flag an issue to fix it. Nevertheless, for aligned types, you could do:

```yml
%YAML 1.1
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/harp-tech/reflex-generator/main/schema/device.json
device: harpy
whoAmI: 0000
firmwareVersion: "0.1"
hardwareTargets: "0.0"
registers:
  Accelerometer:
    address: 32
    type: S16
    length: 3
    access: Event
    payloadSpec:
      X:
        offset: 0
        description: Represents the x-coordinate of the payload.
      Y:
        offset: 1
        description: Represents the y-coordinate of the payload.
      Z:
        offset: 2
        description: Represents the z-coordinate of the payload.
```

This will generate in the high-level interface the type `AccelerometerPayload` with the following signature (edited for conciseness):

```c#
public struct AccelerometerPayload
{
    public AccelerometerPayload(short x, short y, short z)
    {
        X = x;
        Y = y;
        Z = z;
    }

    public short X;
    public short Y;
    public short Z;
}
```

And the auto-generated converters:

```c#
static AccelerometerPayload ParsePayload(short[] payload)
{
    AccelerometerPayload result;
    result.X = payload[0];
    result.Y = payload[1];
    result.Z = payload[2];
    return result;
}

static short[] FormatPayload(AccelerometerPayload value)
{
    short[] result;
    result = new short[3];
    result[0] = value.X;
    result[1] = value.Y;
    result[2] = value.Z;
    return result;
}
```

It is actually possible using the message manipulation API to marshal arbitrary payload structs directly (with the equivalent of `memcpy`), and having an easy way to specify something like this in the spec is definitely interesting. I think I have a solution but need to go through a few edge cases more carefully to make sure it will be workable. Thanks for the push! I'll post here once I have something more complete.

_Originally posted by @glopesdev in https://github.com/harp-tech/protocol/discussions/27#discussioncomment-5994453_

**Comment by glopesdev** [comment]
Diving further into this issue, I can see two possible options which we can discuss at the next SRM.

### Bulk conversion of array payload

The payload of a Harp message is always available as a `byte[]`, so as long as the heterogeneous structure is well-defined and matches the binary layout of the message payload, a bulk conversion might be efficient, e.g. see https://github.com/bonsai-rx/bonsai/pull/2110 and example `ParsePayload` below:

```c#
unsafe static BinaryDataPayload ParsePayload(byte[] payload)
{
    BinaryDataPayload result;
    var resultPtr = &result;
    fixed (byte* payloadPtr = payload)
        Buffer.MemoryCopy(payloadPtr, resultPtr, sizeof(BinaryDataPayload), payload.Length);
    return result;
}
```

### Generalized conversion following payload specification

We could generalize the existing conversion procedure and expand it to allow more flexible assignment. Reusing the existing mechanism would naturally extend all bit masking and handling to heterogeneous types. Although less efficient than the bulk copy conversion presented above, this has the flexibility of allowing many more possible conversion logics.

The main missing ingredient would be to allow specifying the `length` of a `payloadSpec`. This new attribute would be interpreted in terms of the native `type` of the register and used to slice the array prior to the conversion proper. This would allow for example reading multi-byte integers from a byte array payload, or more complex packing of primitives (e.g. nesting).

Example:

```yml
registers:
  BinaryData:
    address: 32
    type: U8
    length: 5
    access: Event
    payloadSpec:
      OperationMode:
        offset: 0
        maskType: OperationMode
        mask: 0x3
      DumpRegisters:
        offset: 0
        interfaceType: bool
        mask: 0x8
      Counter:
        offset: 1
        length: 4
        interfaceType: int
```

The above would generate the payload:

```c#
public struct BinaryDataPayload
{
    public OperationMode OperationMode;
    public bool DumpRegisters;
    public int Counter;
}
```

Alternatively, we could support both approaches by allowing an attribute toggle in the device metadata YML file.
